### ISSUE TITLE
Some checks/steps/etc should be platform-specific

### ISSUE THREAD

**Issue by sax** [synchronal/medic-rs#11]
Tools such as homebrew are specific to macOS. When using medic on other platforms, certain checks should be automatically skipped.

It makes more sense to me to specify this in the medic configuration, rather than forcing each extension to handle it... one may not want to install the `medic-ext-homebrew` extension at all in Linux or FreeBSD, for example.

``` toml
[doctor]
checks = [
  {check = "homebrew", platform = ["Darwin"]},
]
```
