### ISSUE TITLE
Shell checks do not expand glob patterns

### ISSUE THREAD

**Issue by sax** [synchronal/medic-rs#9]
``` toml
[audit]
checks = [
  {name = "Format YAML", shell = "yamlfmt -lint **/*.yml", remedy = "yamlfmt **/*.yml"},
]
```

The check looks for single file matching the string literal `**/*.yml`. Since no file exists, the lint passes.
